---
title: "Regulating foreign banks"
description: Working Paper
date: 09/01/2020
output: distill::distill_article
preview: https://cdn.pixabay.com/photo/2020/03/18/20/01/frankfurt-4945405_960_720.jpg
categories: 
  - Banking
---

The role of foreign banks in the U.S. economy has been a point of practical concern historically (Do foreign banks have a competitive advantage over U.S. banks?) and recently (Do foreign banks expose U.S. taxpayers to risks originating in foreign economies?) While the role of foreign banks in emerging and developing economies has attracted the attention of policymakers and academics, reports that the Federal Reserve channeled billions in loans to foreign banks generated national news headlines in 2011 and triggered a (brief) push for greater scrutiny of foreign banks in the United States. What accounts for major changes in U.S. regulation of foreign banks? How have these rules changed as anxiety about financial crisis has been replaced with an appetite for global capital? What can the US case tell us more generally how internationally active banks impact and are impacted by domestic politics? The only conditions that seem to favor regulatory scrutiny are a rare combination of crisis or scandal (high public attention), outflows of capital from US markets, and a broader government commitment to regulatory reform.


[Click here](https://jkcorder.github.io/papers/apsa2020jkc.pdf) to read the paper.


