---
title: "College financing and persistence to the second year"
description: Working paper. With Kathyrn Corder and Tracy Pattok
date: 07/01/2005
output: distill::distill_article
preview: https://jkcorder.github.io/images/air.png
categories:
  - Other public policy
---

This paper examines second year persistence rates of students receiving various types of financial assistance. We use aggregate data and new methods of ecological inference to uncover individual-level relationships between financial aid and student persistence. We
combine data on the proportion of students receiving various types of aid reported in the Integrated Post Secondary Education Data System [IPEDS] with second year persistence rates reported to the Consortium for Student Retention Data Exchange [CSRDE]. 

We find that links between aid received and persistence vary across both forms of aid and type of institution. At highly selective institutions, students with federal aid persist at a much lower rate than other students, but students with loans, institutional aid, and state
aid persist at similar rates. At less selective institutions, students with institutional aid or
state aid persist at a lower rate than other students, but students with loans or federal aid persist at similar rates. The varying effects observed across institutions explain some of the weak or contradictory findings that are reported in existing research. 

The paper was originally presented at the 2005 Annual Forum of the Association for Institutional Research, San Diego, CA. June, 2005. It is cited occasionally in the literature on persistence and graduation.  [Click here](https://jkcorder.files.wordpress.com/2017/02/corder_air_2005.pdf) to read the paper.


