---
title: "The Impact of the 19th Amendment"
description: Mischiefs of Faction.  With Christina Wolbrecht
date: 08/26/2020
preview: https://static.wixstatic.com/media/848e88_117a3464504f445587f26ed6ba4cd2c3~mv2.jpg/v1/fill/w_120,h_120,al_c,q_80,usm_0.66_1.00_0.01/WmJ7XgZW_400x400.webp
output: distill::distill_article
categories: 
  - Women and politics
---

...no sooner had women began entering polling places in 1920 than observers began declaring women’s suffrage a “failure.” In what we might think of as a historical version of a Twitter hot-take, outlets ranging from Good Housekeeping (“Is Woman’s Suffrage a Failure?”) to Harper’s Magazine (“Is Woman-Suffrage a Failure?”) and The Century (“Are Women a Failure in Politics?”) addressed this claim in the early 1920s. In the words of journalist Frederick Lew Allen in 1931: “[The American woman] won the suffrage in 1920. She seemed, it is true, to be very little interested in it once she had it; she voted, but mostly as the unregenerate men about her did.”

Allen had the facts right: Women did not initially take up their right to vote in the same numbers as men. When women did vote, their choices were little different from those of long-enfranchised men, a pattern many attributed to husbands telling their wives how to vote. Most of the more ambitious promises and warnings about women’s suffrage—both utopia and apocalypse—never materialized.

One hundred years later, we know a lot more about how women actually vote. Women are now more likely to turn out to vote than men. While husbands and wives still generally vote for the same candidates, few assume women take direction from their husbands. In fact, the most popular and persistent media narrative is that women are different; in particular, more likely than to favor Democratic candidates. Given these (new) facts and the longer view, how should we evaluate the impact of the 19th Amendment? What did the 19th Amendment do?

[Click here](https://www.mischiefsoffaction.com/post/19th-amendment) to read the essay.



