---
title: "Turning Rights into Ballots: The Uneven Integration of Women into Electoral Politics after Suffrage"
description: PS Political Science and Politics. With Christina Wolbrecht
date: 07/10/2020
output: distill::distill_article
preview: https://static.cambridge.org/covers/PSC_0_0_0/ps-political-science-and-politics.jpg
categories: 
  - Women and politics
---

After a more than seven-decade battle, American women secured the right to vote in August 1920. The struggle for women to have a voice in elections was not over, however. The Nineteenth Amendment states that “The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex.” The amendment gives Congress the power to enforce the law by appropriate legislation. It does not, however, empower or charge any government office or actor with ensuring that women can and do cast ballots. This article argues that this reality, often taken for granted, has serious implications for both the incorporation of women into the electorate and the representation of their political interests.

[Click here](https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/abs/turning-rights-into-ballots-the-uneven-integration-of-women-into-electoral-politics-after-suffrage/700F278D72E5408C3845A43381DF31DD) to check out the article.



